### ISSUE TITLE
Does not work on Yosemite 10.10.1

### ISSUE THREAD

**Issue by chrisblackstone** [d235j/GVFixer#2]
This worked perfectly for me with 10.10, but now that 10.10.1 has been released, it has stopped working and throws the same JSON errors that it did when Yosemite was first released.

**Comment by kalvinwang** [comment]
Just installed 10.10.2 and GV stopped working with the json error-- tried enable/disabling EasySIMBL and deleting/re-adding the account in GV. No good. Anyone else having this issue?
