### ISSUE TITLE
Not working on Mac OS 10.9.5; is it supposed to?

### ISSUE THREAD

**Issue by johnnyutahh** [d235j/GVFixer#6]
It's not working for me on Mac OS 10.9.5. Is it supposed to?
Details here:  http://apple.stackexchange.com/q/189576/13179

**Comment by balr0g** [comment]
Unfortunately Google has made changes that make this no longer work.

**Comment by d235j** [comment]
Unfortunately Google has made changes that make this no longer work.

**Comment by johnnyutahh** [comment]
GVFixer no longer works on 10.9.5, or GVFixer no longer works (with Google), period?

**Comment by d235j** [comment]
GVFixer no longer works on any OS.

**Comment by johnnyutahh** [comment]
Thanks d235j for updating the main README. You might also want to update the download/releases page at https://github.com/d235j/GVFixer/releases , which some people (like me) my have bookmarked.

Question: does anyone know the date/timeframe when Google made the changes that broke GVFixer?

**Comment by d235j** [comment]
Updated.
See #5 for that information. Would be nice to fix it, but code patching is messy enough as-is :(
